name: CI

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      - githubactions
  pull_request:
    branches: 
      - githubactions

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/jumaanr/devopslearn23
            azure-pipeline-name: 'jumaanr.gitapp'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}